2024-08-22 18:52:20,523 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:52:20,523 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:52:30,311 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:52:30,312 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:52:40,315 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:52:40,316 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:52:46,013 - logger - INFO - /start command received from user 529675743
2024-08-22 18:52:49,609 - logger - INFO - User 529675743 selected topic: Быкующий\U0001f403\U0001f94a
2024-08-22 18:52:51,877 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:52:51,878 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:52:57,742 - logger - INFO - /start command received from user 529675743
2024-08-22 18:52:57,742 - logger - INFO - User 529675743 pressed 'Назад'
2024-08-22 18:53:01,866 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:53:01,866 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:53:11,819 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:53:11,820 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:53:21,866 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:53:21,870 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:53:32,359 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:53:32,366 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:53:43,883 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:53:43,884 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:53:54,408 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:53:54,409 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:54:08,859 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:54:08,860 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:54:31,390 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:54:31,391 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:55:09,877 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:55:09,881 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:56:16,395 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:56:16,396 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:57:22,916 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:57:22,917 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:58:29,433 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:58:29,434 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 18:59:35,947 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 18:59:35,950 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:00:42,471 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:00:42,473 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:01:48,986 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:01:48,988 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:02:55,998 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:02:55,999 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:04:02,512 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:04:02,513 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:05:09,033 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:05:09,035 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:06:15,550 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:06:15,551 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:07:22,058 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:07:22,060 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:08:28,575 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:08:28,576 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:09:35,086 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:09:35,088 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:10:41,616 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:10:41,617 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:11:48,133 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:11:48,134 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-22 19:12:54,645 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-22 19:12:54,647 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanco\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

